version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - yanapa-mongo-data:/data/db
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - yanapa-postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
    ports:
      - "5432:5432"

volumes:
  yanapa-postgres-data:
    driver: local
  yanapa-mongo-data:
    driver: local
